use_frameworks!

platform :ios, '10.0'

target 'AppNetworkManager_Example' do
  pod 'AppNetworkManager', :path => '../'

  target 'AppNetworkManager_Tests' do
    inherit! :search_paths

    
  end
end
